export const mockUsers = [
    {
      id: 1,
      username: "admin_user",
      email:"admin_user@gmail.com",
      password: "admin123",
      role: "admin",
      status: "active",
    },
    {
      id: 2,
      username: "editor_user1",
      email:"editor_user@gmail.com",
      password: "editor123",
      role: "editor",
      status: "active",
    },
    {
      id: 3,
      username: "editor_user2",
      email:"editor_user@gmail.com",
      password: "editor456",
      role: "editor",
      status: "active",
    },
    {
      id: 4,
      username: "viewer_user1",
      email:"viewer_user@gmail.com",
      password: "viewer123",
      role: "viewer",
      status: "active",
    },
    {
      id: 5,
      username: "viewer_user2",
      email:"viewer_user@gmail.com",
      password: "viewer456",
      role: "viewer",
      status: "active",
    },
    {
      id: 6,
      username: "inactive_admin",
      email:"inactive_admin@gmail.com",
      password: "inactive123",
      role: "admin",
      status: "inactive",
    },
  ];
  